/*! 
 * \file      l2_public.c
 * \brief     Part of functions implementing second library layer
 * \details   
 * Main functions for saving and loading memory areas.
 * Dependencies:
 * - "../../include/main/l1.h"
 * - "../../include/main/l2.h"
 * \author    Michal Zidzik
 * \date      02.03.2026
 * \todo Merge with \c l2_private.c
 * \todo Implement \a peripheral functions
 */
#include "../../include/main/l2.h"
#include "../../include/main/l1.h"
#include "../../include/main/l3.h"

bool is_protected(cl_int_t id)
{
    cl_int_t mask = (cl_int_t)1 << (id % ARCHITECTURE_BUS_SIZE);
    if (mask & CL_PROTECTED_MEM[id / ARCHITECTURE_BUS_SIZE]){
        printf("DEBUG is_protected : area %lu is protected\n",id);
        return 1;
    }
    // printf("DEBUG is_protected : area %lu is not protected\n",id);
    return 0;
}

cl_int_t cl_area_on( cl_int_t id,enum Cl_power_mode_t mode, void *custom_d)
{
    cl_int_t i;
    if (!is_protected(id))
    {
        printf("INFO cl_area_on: Area %lu is not protected and therefore won't be loaded\n",id);
        return 0;
    }
    for (i = 0; i < area_backup_table_size; i++){
        if (area_backup_table[i].area->id != id || area_backup_table[i].mode != mode){
            continue;
        }
        printf("DEBUG cl_area_on: Found area with id %lu\n",id);
        cl_load_mem_area(*(area_backup_table[i].area), *(area_backup_table[i].backup_area),RAM_WRITE,NULL);
        break;
    }
    for (i = 0; i < peripheral_backup_table_size; i++){
        if (peripheral_backup_table[i].area->id != id || peripheral_backup_table[i].mode != mode){
            continue;
        }
        printf("DEBUG cl_area_on: Found peripheral with id %lu\n",id);
        cl_load_peripheral(peripheral_backup_table[i].area, *(peripheral_backup_table[i].backup_area),RAM_WRITE,NULL);
        break;
    }
}

cl_int_t cl_area_off( cl_int_t id,enum Cl_power_mode_t mode, void *custom_d)
{
    cl_int_t i;
    /*
    TODO: you should check if its possible to turn it off once you implement current mode variable 
    */
    if (!is_protected(id))
    {
        printf("INFO cl_area_off: Area %lu is not protected and therefore won't be saved\n",id);
        return 0;
    }
    for (i = 0; i < area_backup_table_size; i++){
        if (area_backup_table[i].area->id != id){
            continue;
        }
        printf("DEBUG cl_area_off: Found area with id %lu\n",id);
        cl_save_mem_area(*(area_backup_table[i].area), *(area_backup_table[i].backup_area),RAM_WRITE,NULL);
        break;
    }
    for (i = 0; i < peripheral_backup_table_size; i++){
        if (peripheral_backup_table[i].area->id != id){
            continue;
        }
        printf("DEBUG cl_area_off: Found peripheral with id %lu\n",id);
        cl_save_peripheral(peripheral_backup_table[i].area, *(peripheral_backup_table[i].backup_area),RAM_WRITE,NULL);
        break;
    }
}

cl_int_t cl_protect_all()
{
    cl_int_t i;
    for (i = 0; i < 256; i++){
        cl_protect_memory(i);
    }
}

cl_int_t cl_unprotect_all()
{
    cl_int_t i;
    for (i = 0; i < 256; i++){
        cl_unprotect_memory(i);
    }
}

cl_int_t cl_protect_memory(cl_int_t id)
{
    if (id >= 256){
        printf("WARNING cl_protect_memory: ID should be in range 0 - 255,"
            " please, adjust memory area accordingly\n");
        return 1;
    }
    cl_int_t mask = (cl_int_t)1 << (id % ARCHITECTURE_BUS_SIZE);
    printf("DEBUG cl_protect_memory: id mod ABS is %lu\n",id % ARCHITECTURE_BUS_SIZE);
    printf("DEBUG cl_protect_memory: mask is %lu\n",mask);
    CL_PROTECTED_MEM[id / ARCHITECTURE_BUS_SIZE] |= mask;
    return 0;
}

cl_int_t cl_unprotect_memory(cl_int_t id)
{
    if (id >= 256){
        printf("WARNING cl_unprotect_memory: ID should be in range 0 - 255,"
            " please, adjust memory area accordingly\n");
        return 1;
    }
    cl_int_t mask = ~( (cl_int_t)1 << (id % ARCHITECTURE_BUS_SIZE));
    printf("DEBUG cl_protect_memory: id mod ABS is %lu\n",id % ARCHITECTURE_BUS_SIZE);
    printf("DEBUG cl_protect_memory: mask is %lu\n",mask);
    CL_PROTECTED_MEM[id / ARCHITECTURE_BUS_SIZE] &= mask;
    return 0;
}

/*!
* \brief Finds intersection of two address ranges
* 
* \note This function has been generated by ChatGPT
*/
bool find_match(cl_addr_t start_a1, cl_addr_t end_a1, cl_addr_t start_a2,
                cl_addr_t end_a2, cl_addr_t *start, cl_addr_t *end)
{
    if (start_a1 > end_a1 || start_a2 > end_a2) {
        return false;
    }

    cl_addr_t s = (start_a1 > start_a2) ? start_a1 : start_a2;
    cl_addr_t e = (end_a1   < end_a2)   ? end_a1   : end_a2;

    if (s >= e) {
        return false;
    }
    printf("DEBUG find_match: size of match is %lu\n",e - s);

    if (start) *start = s;
    if (end)   *end   = e;

    return true;
}


cl_int_t cl_change_mode(enum Cl_power_mode_t from_mode, enum Cl_power_mode_t to_mode,void *custom_d)
{
    cl_int_t i;
    for (i = 0; i < area_backup_table_size; i++){
        if (area_backup_table[i].mode == to_mode &&
             is_protected(area_backup_table[i].area->id) &&
            !area_backup_table[i].default_on){
            cl_save_mem_area(*(area_backup_table[i].area), *(area_backup_table[i].backup_area),RAM_WRITE,NULL);
        }
        if (area_backup_table[i].mode == from_mode && 
            is_protected(area_backup_table[i].area->id) && 
            !area_backup_table[i].default_on){
            cl_load_mem_area(*(area_backup_table[i].area), *(area_backup_table[i].backup_area),RAM_WRITE,NULL);
        }
    }
    for (i = 0; i < peripheral_backup_table_size; i++){
        if (peripheral_backup_table[i].mode == to_mode && 
            is_protected(peripheral_backup_table[i].area->id) && 
            !peripheral_backup_table[i].default_on){
            cl_save_peripheral(peripheral_backup_table[i].area, *(peripheral_backup_table[i].backup_area),RAM_WRITE,NULL);
        }
        if (peripheral_backup_table[i].mode == from_mode 
            && is_protected(peripheral_backup_table[i].area->id) 
            && !peripheral_backup_table[i].default_on){
            cl_load_peripheral(peripheral_backup_table[i].area, *(peripheral_backup_table[i].backup_area),RAM_WRITE,NULL);
        }
    }
}
/*
cl_int_t cl_change_mode(enum Cl_power_mode_t from_mode, enum Cl_power_mode_t to_mode,void *custom_d)
{
    cl_int_t on_off_i = 0;
    cl_int_t off_on_i = 0;
    cl_addr_t on_off_mem[40][2] = {}; // list of areas that possibly go from on to off
    cl_addr_t off_on_mem[40][2] = {}; // list of areas that possibly go from off to on

    cl_addr_t start_a,end_a,stump_s,stump_e;
    cl_int_t i,j,k;

    for (i = 0; i < area_mode_table_size; i++){ // loop for every memory range
        if (area_mode_table[i].mode == from_mode && area_mode_table[i].state == ON){
            on_off_mem[on_off_i][0] = area_mode_table[i].start_address; // save first address of range
            on_off_mem[on_off_i][1] = area_mode_table[i].end_address; // save last address of range
            on_off_i++;
        }
        if (area_mode_table[i].mode == from_mode && area_mode_table[i].state == OFF){
            off_on_mem[off_on_i][0] = area_mode_table[i].start_address; // save first address of range
            off_on_mem[off_on_i][1] = area_mode_table[i].end_address; // save last address of range
            off_on_i++;
        }
    }

    for (i = 0; i < area_mode_table_size; i++){ // loop once more for ranges that go from ON <-> OFF
        if (area_mode_table[i].mode == to_mode && area_mode_table[i].state == ON){
            printf("DEBUG cl_change_mode: area on index %lu is possible OFF->ON area\n",i);
            for (j = 0; j < off_on_i; j++){
                if (find_match(off_on_mem[j][0],off_on_mem[j][1],area_mode_table[i].start_address,
                        area_mode_table[i].end_address,&start_a,&end_a)){
                    printf("DEBUG cl_change_mode: area matched with area from table with index %lu\n",j);
                    for (k = 0; k < memory_areas_table_size; k++){
                        if (find_match(start_a,end_a,memory_areas[k]->start_addr,memory_areas[k]->end_addr,&stump_s,&stump_e)){
                            printf("INFO cl_change_mode: Turning on area with id %lu\n",memory_areas[k]->id);
                            cl_area_on(memory_areas[k]->id,to_mode,custom_d);
                        }
                    }
                }
            }
        }
        if (area_mode_table[i].mode == to_mode && area_mode_table[i].state == OFF){
            printf("\n\n\n");
            printf("DEBUG cl_change_mode: area on index %lu is possible ON->OFF area\n",i);
            for (j = 0; j < on_off_i; j++){
                if (find_match(on_off_mem[j][0],on_off_mem[j][1],area_mode_table[i].start_address,
                        area_mode_table[i].end_address,&start_a,&end_a)){
                    printf("DEBUG cl_change_mode: area matched with area from table with index %lu\n",j);
                    for (k = 0; k < memory_areas_table_size; k++){
                        if (find_match(start_a,end_a,memory_areas[k]->start_addr,memory_areas[k]->end_addr,&stump_s,&stump_e)){
                            printf("INFO cl_change_mode: Turning off area with id %lu\n",memory_areas[k]->id);
                            cl_area_off(memory_areas[k]->id,to_mode,custom_d);
                        }
                    }
                }
            }
        }
    }
    printf("DEBUG cl_change_mode: on_off_mem: \n");
    for(i = 0; i < 10; i++){
        printf("[%p, %p]\n",on_off_mem[i][0],on_off_mem[i][1]);
    }
    printf("DEBUG cl_change_mode: off_on_mem: \n");
    for(i = 0; i < 10; i++){
        printf("[%p, %p]\n",off_on_mem[i][0],off_on_mem[i][1]);
    }

}
*/