/*! 
 * \file      l2_public.c
 * \brief     Part of functions implementing second library layer
 * \details   
 * Main functions for saving and loading memory areas.
 * Dependencies:
 * - "../../include/main/l1.h"
 * - "../../include/main/l2.h"
 * \author    Michal Zidzik
 * \date      02.03.2026
 * \todo Merge with \c l2_private.c
 * \todo Implement \a peripheral functions
 */
#include "cl_layer1.h"
#include "cl_layer2.h"
#include "cl_layer3.h"

// TODO: write comments for this function
bool is_protected(cl_int_t id)
{
    cl_int_t mask = (cl_int_t)1 << (id % ARCHITECTURE_BUS_SIZE);
    if (mask & CL_PROTECTED_MEM[id / ARCHITECTURE_BUS_SIZE]){
        printf("DEBUG is_protected : area %lu is protected\n",id);
        return 1;
    }
    // printf("DEBUG is_protected : area %lu is not protected\n",id);
    return 0;
}

cl_int_t cl_area_on( cl_int_t id,enum Cl_power_mode_t mode, void *custom_d)
{
    cl_int_t i;
    if (!is_protected(id))
    {
        printf("INFO cl_area_on: Area %lu is not protected and therefore won't be loaded\n",id);
        return 0;
    }
    for (i = 0; i < area_backup_table_size; i++){
        if (area_backup_table[i].area->id != id || area_backup_table[i].mode != mode){
            continue;
        }
        printf("DEBUG cl_area_on: Found area with id %lu\n",id);
        cl_load_mem_area(*(area_backup_table[i].area), *(area_backup_table[i].backup_area),NULL);
        break;
    }
    for (i = 0; i < peripheral_backup_table_size; i++){
        if (peripheral_backup_table[i].area->id != id || peripheral_backup_table[i].mode != mode){
            continue;
        }
        printf("DEBUG cl_area_on: Found peripheral with id %lu\n",id);
        cl_load_peripheral(peripheral_backup_table[i].area, *(peripheral_backup_table[i].backup_area),NULL);
        break;
    }
}

cl_int_t cl_area_off( cl_int_t id,enum Cl_power_mode_t mode, void *custom_d)
{
    cl_int_t i;
    /*
    TODO: you should check if its possible to turn it off once you implement current mode variable 
    */
    if (!is_protected(id))
    {
        printf("INFO cl_area_off: Area %lu is not protected and therefore won't be saved\n",id);
        return 0;
    }
    for (i = 0; i < area_backup_table_size; i++){
        if (area_backup_table[i].area->id != id){
            continue;
        }
        printf("DEBUG cl_area_off: Found area with id %lu\n",id);
        cl_save_mem_area(*(area_backup_table[i].area), *(area_backup_table[i].backup_area),NULL);
        break;
    }
    for (i = 0; i < peripheral_backup_table_size; i++){
        if (peripheral_backup_table[i].area->id != id){
            continue;
        }
        printf("DEBUG cl_area_off: Found peripheral with id %lu\n",id);
        cl_save_peripheral(peripheral_backup_table[i].area, *(peripheral_backup_table[i].backup_area),NULL);
        break;
    }
}

cl_int_t cl_protect_all()
{
    cl_int_t i;
    for (i = 0; i < 256; i++){
        cl_protect_memory(i);
    }
}

cl_int_t cl_unprotect_all()
{
    cl_int_t i;
    for (i = 0; i < 256; i++){
        cl_unprotect_memory(i);
    }
}

cl_int_t cl_protect_memory(cl_int_t id)
{
    if (id >= 256){
        printf("WARNING cl_protect_memory: ID should be in range 0 - 255,"
            " please, adjust memory area accordingly\n");
        return 1;
    }
    cl_int_t mask = (cl_int_t)1 << (id % ARCHITECTURE_BUS_SIZE);
    printf("DEBUG cl_protect_memory: id mod ABS is %lu\n",id % ARCHITECTURE_BUS_SIZE);
    printf("DEBUG cl_protect_memory: mask is %lu\n",mask);
    CL_PROTECTED_MEM[id / ARCHITECTURE_BUS_SIZE] |= mask;
    return 0;
}

cl_int_t cl_unprotect_memory(cl_int_t id)
{
    if (id >= 256){
        printf("WARNING cl_unprotect_memory: ID should be in range 0 - 255,"
            " please, adjust memory area accordingly\n");
        return 1;
    }
    cl_int_t mask = ~( (cl_int_t)1 << (id % ARCHITECTURE_BUS_SIZE));
    printf("DEBUG cl_protect_memory: id mod ABS is %lu\n",id % ARCHITECTURE_BUS_SIZE);
    printf("DEBUG cl_protect_memory: mask is %lu\n",mask);
    CL_PROTECTED_MEM[id / ARCHITECTURE_BUS_SIZE] &= mask;
    return 0;
}

/*!
* \brief Finds intersection of two address ranges
* 
* \note This function has been generated by ChatGPT
* \note Should be obsolete
* \todo Check if obsolete
*/
bool find_match(cl_addr_t start_a1, cl_addr_t end_a1, cl_addr_t start_a2,
                cl_addr_t end_a2, cl_addr_t *start, cl_addr_t *end)
{
    if (start_a1 > end_a1 || start_a2 > end_a2) {
        return false;
    }

    cl_addr_t s = (start_a1 > start_a2) ? start_a1 : start_a2;
    cl_addr_t e = (end_a1   < end_a2)   ? end_a1   : end_a2;

    if (s >= e) {
        return false;
    }
    printf("DEBUG find_match: size of match is %lu\n",e - s);

    if (start) *start = s;
    if (end)   *end   = e;

    return true;
}


cl_int_t cl_change_mode(enum Cl_power_mode_t from_mode, enum Cl_power_mode_t to_mode,void *custom_d)
{
    cl_int_t i;
    for (i = 0; i < area_backup_table_size; i++){
        if (area_backup_table[i].mode == to_mode &&
             is_protected(area_backup_table[i].area->id) &&
            !area_backup_table[i].default_on){
            cl_save_mem_area(*(area_backup_table[i].area), *(area_backup_table[i].backup_area),NULL);
        }
        if (area_backup_table[i].mode == from_mode && 
            is_protected(area_backup_table[i].area->id) && 
            !area_backup_table[i].default_on){
            cl_load_mem_area(*(area_backup_table[i].area), *(area_backup_table[i].backup_area),NULL);
        }
    }
    for (i = 0; i < peripheral_backup_table_size; i++){
        if (peripheral_backup_table[i].mode == to_mode && 
            is_protected(peripheral_backup_table[i].area->id) && 
            !peripheral_backup_table[i].default_on){
            cl_save_peripheral(peripheral_backup_table[i].area, *(peripheral_backup_table[i].backup_area),NULL);
        }
        if (peripheral_backup_table[i].mode == from_mode 
            && is_protected(peripheral_backup_table[i].area->id) 
            && !peripheral_backup_table[i].default_on){
            cl_load_peripheral(peripheral_backup_table[i].area, *(peripheral_backup_table[i].backup_area),NULL);
        }
    }
}