/*! 
 * \file      l2_public.c
 * \brief     Part of functions implementing second library layer
 * \details   
 * Main functions for saving and loading memory areas.
 * Dependencies:
 * - "../../include/main/l1.h"
 * - "../../include/main/l2.h"
 * \author    Michal Zidzik
 * \date      02.03.2026
 * \todo Merge with \c l2_private.c
 * \todo Implement \a peripheral functions
 */
#include "cl_layer1.h"
#include "cl_layer2.h"
#include "cl_layer3.h"
#include "ulog.h"

// TODO: write comments for this function
bool is_protected(cl_int_t id)
{
    cl_int_t mask = (cl_int_t)1 << (id % ARCHITECTURE_BUS_SIZE);
    if (mask & CL_PROTECTED_MEM[id / ARCHITECTURE_BUS_SIZE]){
        ULOG_DEBUG("is_protected:\tarea %lu is protected",id);
        return 1;
    }
    return 0;
}

// cl_save_f_t save_f = sel_save_f(dst_area.save_type); // choose low-level technique for storing data
// cl_load_f_t load_f = sel_load_f(src_area.save_type); // choose low-level technique for loading data
enum Cl_power_mode_t get_mode()
{
    cl_int_t mode;
    cl_load_f_t load_f = sel_load_f(ma255.save_type);
    load_f(&mode,ma255.end_addr, NULL);
    return (enum Cl_power_mode_t)mode;
}

void write_mode(enum Cl_power_mode_t new_mode)
{
    cl_save_f_t save_f = sel_save_f(ma255.save_type);
    save_f((cl_int_t)new_mode,ma255.end_addr,NULL);
}

    
    

cl_int_t cl_area_on( cl_int_t id,enum Cl_power_mode_t mode, void *custom_d)
{
    cl_int_t i;
    if (!is_protected(id))
    {
        ULOG_INFO("cl_area_on:\tArea %lu is not protected and therefore won't be loaded",id);
        return 0;
    }
    for (i = 0; i < area_backup_table_size; i++){
        if (area_backup_table[i].area->id != id || area_backup_table[i].mode != mode){
            continue;
        }
        ULOG_DEBUG("cl_area_on:\tFound area with id %lu",id);
        cl_load_mem_area(*(area_backup_table[i].area), *(area_backup_table[i].backup_area),NULL);
        break;
    }
    for (i = 0; i < peripheral_backup_table_size; i++){
        if (peripheral_backup_table[i].area->id != id || peripheral_backup_table[i].mode != mode){
            continue;
        }
        ULOG_DEBUG("cl_area_on:\tFound peripheral with id %lu",id);
        cl_load_peripheral(peripheral_backup_table[i].area, *(peripheral_backup_table[i].backup_area),NULL);
        break;
    }
}

cl_int_t cl_area_off( cl_int_t id,enum Cl_power_mode_t mode, void *custom_d)
{
    cl_int_t i;
    /*
    TODO: you should check if its possible to turn it off once you implement current mode variable 
    */
    if (!is_protected(id))
    {
        ULOG_INFO("cl_area_off:\tArea %lu is not protected and therefore won't be saved",id);
        return 0;
    }
    for (i = 0; i < area_backup_table_size; i++){
        if (area_backup_table[i].area->id != id){
            continue;
        }
        ULOG_DEBUG("cl_area_off:\tFound area with id %lu",id);
        cl_save_mem_area(*(area_backup_table[i].area), *(area_backup_table[i].backup_area),NULL);
        break;
    }
    for (i = 0; i < peripheral_backup_table_size; i++){
        if (peripheral_backup_table[i].area->id != id){
            continue;
        }
        ULOG_DEBUG("cl_area_off:\tFound peripheral with id %lu",id);
        cl_save_peripheral(peripheral_backup_table[i].area, *(peripheral_backup_table[i].backup_area),NULL);
        break;
    }
}

cl_int_t cl_protect_all()
{
    cl_int_t i;
    for (i = 0; i < 256; i++){
        cl_protect_memory(i);
    }
}

cl_int_t cl_unprotect_all()
{
    cl_int_t i;
    for (i = 0; i < 256; i++){
        cl_unprotect_memory(i);
    }
}

cl_int_t cl_protect_memory(cl_int_t id)
{
    if (id >= 256){
        ULOG_WARNING("cl_protect_memory:\tID should be in range 0 - 255, please adjust memory area accordingly");
        return 1;
    }
    cl_int_t mask = (cl_int_t)1 << (id % ARCHITECTURE_BUS_SIZE);
    ULOG_DEBUG("cl_protect_memory:\tid mod ABS is %lu",id % ARCHITECTURE_BUS_SIZE);
    ULOG_DEBUG("cl_protect_memory:\tmask is %lu",mask);
    CL_PROTECTED_MEM[id / ARCHITECTURE_BUS_SIZE] |= mask;
    return 0;
}

cl_int_t cl_unprotect_memory(cl_int_t id)
{
    if (id >= 256){
        ULOG_WARNING("cl_unprotect_memory:\tID should be in range 0 - 255, please adjust memory area accordingly");
        return 1;
    }
    cl_int_t mask = ~( (cl_int_t)1 << (id % ARCHITECTURE_BUS_SIZE));
    ULOG_DEBUG("cl_unprotect_memory:\tid mod ABS is %lu",id % ARCHITECTURE_BUS_SIZE);
    ULOG_DEBUG("cl_unprotect_memory:\tmask is %lu",mask);
    CL_PROTECTED_MEM[id / ARCHITECTURE_BUS_SIZE] &= mask;
    return 0;
}

/*!
* \brief Finds intersection of two address ranges
* 
* \note This function has been generated by ChatGPT
* \note Should be obsolete
* \todo Check if obsolete
*/
bool find_match(cl_addr_t start_a1, cl_addr_t end_a1, cl_addr_t start_a2,
                cl_addr_t end_a2, cl_addr_t *start, cl_addr_t *end)
{
    if (start_a1 > end_a1 || start_a2 > end_a2) {
        return false;
    }

    cl_addr_t s = (start_a1 > start_a2) ? start_a1 : start_a2;
    cl_addr_t e = (end_a1   < end_a2)   ? end_a1   : end_a2;

    if (s >= e) {
        return false;
    }
    ULOG_DEBUG("find_match:\tsize of match is %lu",e - s);

    if (start) *start = s;
    if (end)   *end   = e;

    return true;
}


cl_int_t cl_change_mode(enum Cl_power_mode_t from_mode, enum Cl_power_mode_t to_mode,void *custom_d)
{
    cl_int_t i;
    for (i = 0; i < area_backup_table_size; i++){
        if (area_backup_table[i].mode == to_mode &&
             is_protected(area_backup_table[i].area->id) &&
            !area_backup_table[i].default_on){
            cl_save_mem_area(*(area_backup_table[i].area), *(area_backup_table[i].backup_area),NULL);
        }
        if (area_backup_table[i].mode == from_mode && 
            is_protected(area_backup_table[i].area->id) && 
            !area_backup_table[i].default_on){
            cl_load_mem_area(*(area_backup_table[i].area), *(area_backup_table[i].backup_area),NULL);
        }
    }
    for (i = 0; i < peripheral_backup_table_size; i++){
        if (peripheral_backup_table[i].mode == to_mode && 
            is_protected(peripheral_backup_table[i].area->id) && 
            !peripheral_backup_table[i].default_on){
            cl_save_peripheral(peripheral_backup_table[i].area, *(peripheral_backup_table[i].backup_area),NULL);
        }
        if (peripheral_backup_table[i].mode == from_mode 
            && is_protected(peripheral_backup_table[i].area->id) 
            && !peripheral_backup_table[i].default_on){
            cl_load_peripheral(peripheral_backup_table[i].area, *(peripheral_backup_table[i].backup_area),NULL);
        }
    }
}