/*! 
 * \file      use_cases.c
 * \brief     Set of expected use cases for this library
 * \details   
 * Dependencies:
 - "../../include/main/context_manager.h"
 - "use_cases.h"
 * This file is part of library testbench, expanding upon \c tests.c file. While
 * that file focused mostly on 
 * \author    Michal Zidzik
 * \date      02.03.2026
 * \pre       Needs to include config.h with valid configuration declarations (TODO)
 * \note Tests are designed using \a posix pseudo port in mind.
 * \note While I designed tests in this file, many of them were written using GPT or Copilot
 * \todo Break this file into several smaller ones
 */
#include <stdio.h>
// #include "../../platform/posix/context_lib_port.h"
#include "context_manager.h"
#include "use_cases.h"

void print_lram()
{
    cl_int_t i;
    printf("LRAM: \n");
    for (i = 0; i < 50;i++){
        printf("%lu,",LRAM[i]);
    }
    printf("\n");
}

void print_lram2()
{
    cl_int_t i;
    printf("LRAM100+: \n");
    for (i = 0; i < 10;i++){
        printf("%lu,",LRAM[i + 100]);
    }
    printf("\n");
}

void print_rf()
{
    cl_int_t i;
    printf("RF: \n");
    for (i = 0; i < 128; i++){
        printf("%lu,",REGISTER_FILE[i]);
    }
}

// function generated by chat gpt
void print_bits_uint64(cl_int_t x)
{
    for (int64_t i = 63; i >= 0; i--) {
        printf("%lu", (x >> i) & 1);
    }
    printf("\n");
}

void hram_clear()
{
    cl_int_t i;
    for (i = 0; i < 1024; i++){
        HRAM[i] = 0;
    }
}

void lram_clear()
{
    cl_int_t i;
    for (i = 0; i < 1024; i++){
        LRAM[i] = 0;
    }
}

void use_case1_fill()
{
    cl_int_t i,j,k;
    cl_int_t arr1[] = {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20};
    for(i = 0; i < 5; i++){
        HRAM[i] = arr1[i];
    }
    for(i = 0; i < 5; i++){
        HRAM[i + 10] = arr1[i + 5];
    }
    for(i = 0; i < 5; i++){
        HRAM[i + 20] = arr1[i + 10];
    }
    for(i = 0; i < 5; i++){
        HRAM[i + 30] = arr1[i + 15];
    }
}

void use_case1_print()
{
    cl_int_t i;
    printf("ma100:\n");
    for(i = 0; i < 5; i++){
        printf("%lu,",HRAM[i + 0]);
    }
    printf("\n");

    printf("ma101:\n");
    for(i = 0; i < 5; i++){
        printf("%lu,",HRAM[i + 10]);
    }
    printf("\n");
    printf("ma102:\n");
    for(i = 0; i < 5; i++){
        printf("%lu,",HRAM[i + 20]);
    }
    printf("\n");
    printf("ma103:\n");
    for(i = 0; i < 5; i++){
        printf("%lu,",HRAM[i + 30]);
    }
    printf("\n");
}

/*
base example of data storage and load
//TODO: it should also contain RUN-VLLS transition
// as well as realistic dealing with areas reinitialization
*/
/*
void use_case1()
{
    cl_clear_mem_area(ma10,NULL);
    cl_clear_mem_area(ma11,NULL);
    cl_clear_mem_area(ma1,NULL);
    cl_protect_memory(11);
    cl_protect_memory(255);
    cl_protect_memory(100);
    cl_protect_memory(101);
    cl_protect_memory(102);
    cl_protect_memory(103);

    cl_int_t i,j,k;
    use_case1_fill();
    use_case1_print();
    cl_write_mode(RUN);
    cl_change_mode(STOP,NULL);
    print_lram();
    print_lram2();
    hram_clear();
    cl_change_mode(RUN,NULL);
    use_case1_print();
    cl_unprotect_memory(102);
    cl_unprotect_memory(103);
    cl_change_mode(STOP,NULL);
    hram_clear();
    cl_change_mode(RUN,NULL);
    use_case1_print();
    cl_protect_memory(102);
    cl_protect_memory(103);
    use_case1_fill();
    cl_change_mode(STOP,NULL);
    cl_change_mode(VLLS,NULL);
    print_rf();
    lram_clear();
    hram_clear();
    cl_clear_mem_area(ma10,NULL);
    cl_clear_mem_area(ma11,NULL);
    cl_change_mode(STOP,NULL);
    cl_change_mode(RUN,NULL);
    use_case1_print();
    print_lram2();
}
    */

/* ===== Use case  2

*/
